version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.13.0

commands:
  install_libs:
    steps:
      - restore_cache:
          keys:
            - v2-yarn-sha-{{ checksum "yarn.lock" }}
            - v2-yarn-sha-
      - run:
          name: Install js dependencies
          command: yarn install

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - install_libs
      - save_cache:
          key: v2-yarn-sha-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/v4
  test:
    <<: *defaults
    steps:
      - checkout
      - install_libs
      - run:
          name: Run linter
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
